### ISSUE TITLE
Carte - Amilly Field - Description : Absente

### ISSUE THREAD

**Issue by Mithiriath** [Mithiriath/coh2-correction-traduction-fr#8]
Carte - Amilly Field - Description : Absence de description sur la carte.

![20210502104851_1](https://user-images.githubusercontent.com/4489876/117686094-d162a800-b1b6-11eb-8acf-0915fe3e9f68.jpg)

Crédit : Piterboys

**Comment by Mithiriath** [comment]
Description en anglais ajoutée. Source : https://steamcommunity.com/sharedfiles/filedetails/?id=1857890839

Il faut maintenant la traduire.

**Comment by Piterboys** [comment]
Traduction du texte : Alors que l'été cède la place à l'automne, une petite force alliée s'installe à la périphérie de la petite ville française d'Amilly, elle est chargée de réparer une section de voie ferrée détruite par les forces allemandes en retraite. Cette voie ferrée sera essentielle pour maintenir les approvisionnements à l'avant.
